#Makefile for building project for Windows
OBJS=main.o 3dm.o gl.o basic.o vbo.o app.o glad/glad.o
O=corridor.exe

CC=gcc
CFLAGS=-nocpp -g3 -Og -pipe -m64 -march=native -mtune=native -DWINDOWS=1
CFLAGS+=-ftree-vectorize -ffast-math -funroll-loops
LDFLAGS=-lmingw32 -lSDL2main -lSDL2 -lm -mwindows

all: ${O}

clean:
	@rm -fv ${O} ${OBJS}

${O}: ${OBJS}
	${CC} $^ -o $@ ${LDFLAGS}
